export const items = [
    {
        id: 1,
        category: 'mobiles',
        title: "Apple iPhone 14",
        imgSrc: 'https://amzn.to/3PuckZp',
        description: 'Apple iPhone 14 (128 GB) - Blue',
        price: '89999',
    },
    {
        id: 5,
        category: 'laptops',
        title: "Xiomi [Smartchoice] Notebookpro",
        imgSrc: 'https://m.media-amazon.com/image/I/71TPda7cwUL._SL1500_.jpg',
        amazonLink: 'https://amzn.to/3EzeQaC',
        description: 'Xiaomi [Smartchice] Notebookpro',
        price: '49999',
    },
    {
        id: 7,
        category: 'tablets',
        title: "Xiaomi Pad 6",
        imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
        amazoneLink: 'https://amzn.to/3ZeNRdY',
        description: 'Xiaomi Pad 6|Qualcomm Snapdragon 870|',
        price: '29999',
    },
    {
        id: 2,
        category: 'mobiles',
        title: "Apple iPhone 11",
        imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazoneLink: 'https//amzn.to/44MiYi6',
        description: 'Apple iPhone 11 (64GB) - White',
        price: '79999',
    },
    {
        id: 6,
        category: 'tablets',
        title: "Lenove Tab P12 Pro AMOLED",
        imgSrc: 'https//m.media-amazon.com/images/I/51b9LjzmPCL._SLL1080_.jpg',
        amazonLink: 'https://amzn.to/3RabsdH',
        description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Strom Grey with Precision Pen 3',
        price: '19999',
    },
    {
        id: 3,
        category: 'mobile',
        title: "Apple iphone 13",
        imgSrc: 'https://m.media-amazon.com/images/I/71cb2xkN5qL._SL1500_.jpg',
        amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Apple iPhone 13 (128GB) - Blue',
        price: '69999',
    },
    {
        id: 4,
        category: 'laptops',
        tittle: "Lenove IdeaPad Slim 5",
        imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
        amazoneLink: 'https://amzn.to/4JsK4r',
        description: 'Lenove IdeaPad Slim 5 Intel Core is 12450H 14" (35.5cm)',
        price: '29999',
    },
    {
        id:9,
        category:'tablets',
        title:"Samsung Galaxy Tab A8",
        imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
        amazonLink:'https://amzn.to/3Pdsh4F',
        description:'SSamsung Galaxy Tab A8 26.69cm (10.5 imch) Display,RAM 4GB,ROM 64 GB Expandable, Wi-Fi Tablets,Grey,(SM-X200NZAEINU)',
        price: '49999',
    },
    {
        id: 8,
        category: 'laptops',
        tittle:"Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
        amazonLink:'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina displlay, ',
        price: '89999',
    }

    
]